FROM golang:1.21-alpine AS BUILDER
WORKDIR /gvb

COPY go.mod go.mod
COPY go.sum go.sum
RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go mod download

COPY . .
RUN cd cmd && go build -o server . 

FROM alpine:3.19
ENV WORK_PATH /gvb
WORKDIR ${WORK_PATH}
COPY --from=BUILDER ${WORK_PATH}/cmd/server .
COPY --from=BUILDER ${WORK_PATH}/config.docker.yml .
# 离线IP 数据管理框架和定位库
COPY --from=BUILDER ${WORK_PATH}/assets/ip2region.xdb ./assets/ip2region.xdb 

EXPOSE 8765

ENTRYPOINT ./server -c config.docker.yml